include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-inference: true
    strict-raw-types: true
  errors:
    avoid_print: warning
    unnecessary_import: warning
    always_declare_return_types: error

linter:
  rules:
    - always_declare_return_types
    - prefer_final_locals
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - use_build_context_synchronously
    - unnecessary_late
    - avoid_redundant_argument_values

