name: blessed_fam
description: BlessedFam - Attendance and Fellowship Performance Tracker
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  supabase_flutter: ^2.6.0
  go_router: ^14.2.7
  google_fonts: ^6.2.1
  intl: ^0.19.0
  uuid: ^4.5.1
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/


