name: blessed_fam
description: BlessedFam - Attendance and Fellowship Performance Tracker
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  supabase_flutter: ^2.6.0
  go_router: ^14.2.7
  google_fonts: ^6.2.1
  intl: ^0.19.0
  uuid: ^4.5.1
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

# App Icon Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  
  # Adaptive icon for Android
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/logo.png"

# Splash Screen Configuration - Minimal/No splash
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icons/logo.png
  android: true
  ios: true
  
  # Remove splash screen quickly
  android_12:
    color: "#FFFFFF"
    image: assets/icons/logo.png
  
  # Minimal duration
  fullscreen: false
  android_gravity: center
  ios_content_mode: center


